package com.example.util

import android.content.Context
import android.content.SharedPreferences
import androidx.compose.runtime.compositionLocalOf
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

enum class AppLanguage(val code: String, val displayName: String, val flagEmoji: String) {
    SPANISH("es", "Español", "🇪🇸"),
    ENGLISH("en", "English", "🇺🇸"),
    PORTUGUESE("pt", "Português", "🇧🇷");

    companion object {
        fun fromCode(code: String): AppLanguage {
            return entries.firstOrNull { it.code.equals(code, ignoreCase = true) } ?: SPANISH
        }
    }
}

data class AppStrings(
    // Common
    val appName: String,
    val appSubtitle: String,
    val appTagline: String,
    val back: String,
    val cancel: String,
    val save: String,
    val confirm: String,
    val delete: String,
    val close: String,
    val ready: String,

    // Welcome Screen
    val welcomeTitle: String,
    val welcomeSubtitle: String,
    val welcomeDescription: String,
    val welcomeLogin: String,
    val welcomeRegister: String,
    val welcomeGuest: String,
    val welcomeFeaturesTitle: String,
    val featureDistanceTitle: String,
    val featureDistanceDesc: String,
    val featureAreaTitle: String,
    val featureAreaDesc: String,
    val featureVolumeTitle: String,
    val featureVolumeDesc: String,

    // Auth
    val loginTitle: String,
    val loginSubtitle: String,
    val registerTitle: String,
    val registerSubtitle: String,
    val emailLabel: String,
    val emailPlaceholder: String,
    val passwordLabel: String,
    val passwordPlaceholder: String,
    val nameLabel: String,
    val namePlaceholder: String,
    val confirmPasswordLabel: String,
    val rememberMe: String,
    val forgotPassword: String,
    val noAccountPrompt: String,
    val alreadyAccountPrompt: String,
    val socialDivider: String,
    val socialRegisterDivider: String,
    val acceptTerms: String,

    // Home
    val homeHeaderTitle: String,
    val homeHeaderSubtitle: String,
    val modesTitle: String,
    val modeDistanceTitle: String,
    val modeDistanceDesc: String,
    val modeAreaTitle: String,
    val modeAreaDesc: String,
    val modeVolumeTitle: String,
    val modeVolumeDesc: String,
    val statsTitle: String,
    val statsTotal: String,
    val statsDistance: String,
    val statsArea: String,
    val statsVolume: String,
    val quickActionsTitle: String,
    val actionCalibration: String,
    val actionCalibrationDesc: String,
    val actionHistory: String,
    val actionHistoryDesc: String,
    val actionSettings: String,
    val actionSettingsDesc: String,
    val recentMeasurementsTitle: String,
    val viewAll: String,
    val noMeasurementsYet: String,
    val startFirstMeasurement: String,
    val drawerMenu: String,
    val drawerLanguage: String,
    val drawerPrivacy: String,
    val drawerTerms: String,
    val drawerLogout: String,

    // Measure
    val measureDistMode: String,
    val measureAreaMode: String,
    val measureVolMode: String,
    val markPointBtn: String,
    val saveBtn: String,
    val clearBtn: String,
    val calibrateBtn: String,
    val finishScan: String,
    val startScan: String,
    val heightLabel: String,
    val pointsCount: String,
    val pointCountSingle: String,
    val liveDistanceBadge: String,
    val onboardingTip: String,
    val saveDialogTitle: String,
    val saveTitlePlaceholder: String,

    // Settings
    val settingsTitle: String,
    val languageSetting: String,
    val languageSubtitle: String,
    val selectLanguage: String,
    val unitSystem: String,
    val unitSystemMetric: String,
    val unitSystemImperial: String,
    val showTrackingGrid: String,
    val showTrackingGridDesc: String,
    val highQualityMode: String,
    val highQualityModeDesc: String,
    val hapticFeedback: String,
    val hapticFeedbackDesc: String,
    val measurementSounds: String,
    val measurementSoundsDesc: String,
    val manageSubscription: String,
    val manageSubscriptionSubtitle: String,
    val signOut: String,
    val appVersion: String,

    // History
    val historyTitle: String,
    val historySearchPlaceholder: String,
    val filterAll: String,
    val filterDistance: String,
    val filterArea: String,
    val filterVolume: String,
    val exportPdf: String,
    val exportCsv: String,
    val copyData: String,
    val share: String,
    val deleteRecord: String,
    val clearAll: String,
    val noResultsFound: String,

    // Additional UI strings
    val deleteConfirmTitle: String = clearAll,
    val deleteConfirmMessage: String = "Confirma la eliminación de los registros.",
    val history: String = historyTitle,
    val export: String = share,
    val searchPlaceholder: String = historySearchPlaceholder,
    val settings: String = settingsTitle,
    val language: String = drawerLanguage,
    val logout: String = drawerLogout,
    val saveMeasurement: String = saveDialogTitle,
    val baseArea: String = "Área base",
    val heightText: String = "Altura",
    val saveTitle: String = "Etiqueta / Nota",
    val calibration: String = actionCalibration,
    val material: String = "Material",
    val pointInstruction: String = onboardingTip,
    val addPoint: String = markPointBtn,
    val totalDistance: String = "Distancia Total",
    val calculatedArea: String = "Área Calculada",
    val estimatedVolume: String = "Volumen Estimado",
    val locateStartingPoint: String = "Ubique el Punto de Partida",
    val pointSetWalkToEnd: String = "Punto fijado. Diríjase al punto final",
    val bothPointsSet: String = "Puntos fijados",
    val stopScan: String = "Detener Escaneo",
    val preparingScan: String = "Preparando...",
    val scan3D: String = "Escanear 3D",
    val undo: String = "Deshacer",
    val reset: String = "Reiniciar",
    val mappingEnvironment: String = "Mapeando Entorno",
    val mappingEnvironmentDesc: String = "Mueve tu teléfono lentamente de lado a lado apuntando a las superficies que deseas medir para que el sistema las detecte.",
    val understood: String = "Entendido",
    val pointCloudViewer: String = "Visor 3D",
    val pointCloudCount: String = "Puntos LiDAR",
    val clearCloud: String = "Limpiar Nube",
    val simulateScan: String = "Simular 3D",
    val scanningLaser: String = "Escaneando nube de puntos LiDAR...",
    val exportPly: String = "Exportar PLY / OBJ",

    val scanGuideTitle: String = "Guía de Escaneo y Precisión 3D",
    val scanGuideSubtitle: String = "Cómo obtener mediciones milimétricas con AR & LiDAR",
    val scanGuideStep1Title: String = "1. Mapeo y Detección de Superficies",
    val scanGuideStep1Desc: String = "Mueve el teléfono suavemente de lado a lado con una inclinación de 45° hacia la superficie. Evita movimientos bruscos hasta que los puntos amarillos de la cuadrícula cubran el área.",
    val scanGuideStep2Title: String = "2. Luz y Textura Óptima",
    val scanGuideStep2Desc: String = "Asegúrate de contar con buena iluminación. Los sensores AR necesitan textura visible (suelo, paredes, madera, alfombra). Evita vidrios transparentes o espejos lisos.",
    val scanGuideStep3Title: String = "3. Escaneo 3D y Nube de Puntos",
    val scanGuideStep3Desc: String = "Para medir volúmenes o acopios en 3D, camina despacio alrededor del objeto a 1–3 metros de distancia para que el láser capture todas sus caras.",
    val scanGuideStep4Title: String = "4. Calibración y Medición Precisa",
    val scanGuideStep4Desc: String = "Alinea la retícula central exactamente en el punto deseado. Usa la herramienta de Calibración con una tarjeta o referencia estándar para alcanzar una precisión del 99.8%.",
    val scanGuideInteractiveTest: String = "Simulador de Escaneo Interactivo",
    val scanGuideInteractiveHint: String = "Arrastra el dedo sobre la superficie para simular el barrido láser del sensor LiDAR y detectar puntos espaciales.",
    val scanGuideSurfaceDetected: String = "¡Superficie Mapeada con Alta Precisión!",
    val scanGuideSurfaceScanning: String = "Mapeando superficie... Desliza para escanear",
    val scanGuideStartMeasuring: String = "¡Comenzar a Medir!",
    val scanGuideNext: String = "Siguiente",
    val scanGuidePrev: String = "Anterior",
    val scanGuideSkip: String = "Omitir",
    val scanGuideDoNotShowAgain: String = "No volver a mostrar automáticamente",
    val scanGuideHelpTooltip: String = "Guía de Medición 3D"
)

val SpanishStrings = AppStrings(
    appName = "METRAX AR",
    appSubtitle = "SISTEMA AR DE MEDICIÓN",
    appTagline = "SISTEMA DE MEDICIÓN Y FOTOGRAMETRÍA 3D",
    back = "Volver",
    cancel = "Cancelar",
    save = "Guardar",
    confirm = "Confirmar",
    delete = "Eliminar",
    close = "Cerrar",
    ready = "LISTO",

    welcomeTitle = "METRAX AR",
    welcomeSubtitle = "SISTEMA DE MEDICIÓN Y FOTOGRAMETRÍA 3D",
    welcomeDescription = "Mapeá superficies, calculá distancias, áreas y volúmenes de acopios en tiempo real con Realidad Aumentada.",
    welcomeLogin = "Iniciar Sesión",
    welcomeRegister = "Registrarse",
    welcomeGuest = "Continuar como Invitado",
    welcomeFeaturesTitle = "MODOS PROFESIONALES DE MEDICIÓN",
    featureDistanceTitle = "Medición Lineal y Distancia",
    featureDistanceDesc = "Segmentos continuos con precisión milimétrica",
    featureAreaTitle = "Cálculo de Área y Perímetro",
    featureAreaDesc = "Superficies poligonales automáticas en pisos y paredes",
    featureVolumeTitle = "Estimación de Volumen 3D",
    featureVolumeDesc = "Nube de puntos LiDAR / fotogrametría para materiales",

    loginTitle = "Bienvenido de nuevo",
    loginSubtitle = "Ingresá con tu cuenta para acceder a tus mediciones",
    registerTitle = "Crear cuenta",
    registerSubtitle = "Registrate para sincronizar proyectos y mediciones en la nube",
    emailLabel = "Correo electrónico",
    emailPlaceholder = "ejemplo@metrax.com",
    passwordLabel = "Contraseña",
    passwordPlaceholder = "Ingresá tu contraseña",
    nameLabel = "Nombre completo",
    namePlaceholder = "Ingresá tu nombre",
    confirmPasswordLabel = "Confirmar contraseña",
    rememberMe = "Recordarme",
    forgotPassword = "¿Olvidaste tu contraseña?",
    noAccountPrompt = "¿No tenés cuenta?",
    alreadyAccountPrompt = "¿Ya tenés cuenta?",
    socialDivider = "o continuar con",
    socialRegisterDivider = "o registrarse con",
    acceptTerms = "Acepto los Términos y Condiciones del servicio",

    homeHeaderTitle = "Medición en Campo",
    homeHeaderSubtitle = "Cámara AR con detección de planos y fotogrametría 3D",
    modesTitle = "Modos de Medición",
    modeDistanceTitle = "Distancia",
    modeDistanceDesc = "Líneas rectas y polilíneas continuas",
    modeAreaTitle = "Área",
    modeAreaDesc = "Superficies poligonales y perímetros",
    modeVolumeTitle = "Volumen",
    modeVolumeDesc = "Nubes de puntos para acopios y objetos",
    statsTitle = "Resumen de Mediciones",
    statsTotal = "Total",
    statsDistance = "Distancia",
    statsArea = "Área",
    statsVolume = "Volumen",
    quickActionsTitle = "Herramientas Rápidas",
    actionCalibration = "Calibrar Sensor",
    actionCalibrationDesc = "Ajustá el factor de escala con referencias reales",
    actionHistory = "Historial Completo",
    actionHistoryDesc = "Explorar mediciones guardadas y exportar",
    actionSettings = "Configuración",
    actionSettingsDesc = "Unidades, sensor háptico y preferencias",
    recentMeasurementsTitle = "Mediciones Recientes",
    viewAll = "Ver todas",
    noMeasurementsYet = "Aún no hay mediciones registradas",
    startFirstMeasurement = "Iniciá una medición usando los botones superiores",
    drawerMenu = "Menú",
    drawerLanguage = "Idioma",
    drawerPrivacy = "Política de Privacidad",
    drawerTerms = "Acuerdo del Cliente",
    drawerLogout = "Cerrar Sesión",

    measureDistMode = "DISTANCIA",
    measureAreaMode = "ÁREA",
    measureVolMode = "VOLUMEN",
    markPointBtn = "Marcar Punto",
    saveBtn = "Guardar",
    clearBtn = "Limpiar",
    calibrateBtn = "Calibrar",
    finishScan = "Finalizar Escaneo",
    startScan = "Iniciar Escaneo LiDAR",
    heightLabel = "Altura del cuerpo",
    pointsCount = "puntos marcados",
    pointCountSingle = "punto marcado",
    liveDistanceBadge = "en vivo",
    onboardingTip = "Apuntá la cámara a una superficie con buena luz para detectar planos",
    saveDialogTitle = "Guardar Medición",
    saveTitlePlaceholder = "Ej: Pared Living, Terreno, Acopio Arena",

    settingsTitle = "Configuración",
    languageSetting = "Idioma de la App",
    languageSubtitle = "Español, English, Português",
    selectLanguage = "Seleccionar Idioma",
    unitSystem = "Sistema de Unidades",
    unitSystemMetric = "Métrico (m, cm, m², m³)",
    unitSystemImperial = "Imperial (ft, in, ft², ft³)",
    showTrackingGrid = "Mostrar Malla de Detección",
    showTrackingGridDesc = "Muestra cuadrícula de puntos en planos detectados",
    highQualityMode = "Modo Alta Precisión",
    highQualityModeDesc = "Mayor procesamiento para estabilidad y fotogrametría",
    hapticFeedback = "Respuesta Háptica",
    hapticFeedbackDesc = "Vibrar al colocar puntos y calibrar",
    measurementSounds = "Sonidos de Medición",
    measurementSoundsDesc = "Emitir tono de confirmación al fijar nodo",
    manageSubscription = "Plan Profesional",
    manageSubscriptionSubtitle = "Plan Empresarial Activo",
    signOut = "Cerrar Sesión",
    appVersion = "Metrax AR v1.2.0 • Multi-idioma & Responsive",

    historyTitle = "Historial de Mediciones",
    historySearchPlaceholder = "Buscar mediciones guardadas...",
    filterAll = "Todas",
    filterDistance = "Distancia",
    filterArea = "Área",
    filterVolume = "Volumen",
    exportPdf = "Exportar Informe PDF",
    exportCsv = "Exportar Datos CSV",
    copyData = "Copiar Datos",
    share = "Compartir",
    deleteRecord = "Eliminar Medición",
    clearAll = "Borrar Todo",
    noResultsFound = "No se encontraron mediciones"
)

val EnglishStrings = AppStrings(
    appName = "METRAX AR",
    appSubtitle = "AR MEASUREMENT SYSTEM",
    appTagline = "3D PHOTOGRAMMETRY & MEASUREMENT SYSTEM",
    back = "Back",
    cancel = "Cancel",
    save = "Save",
    confirm = "Confirm",
    delete = "Delete",
    close = "Close",
    ready = "READY",

    welcomeTitle = "METRAX AR",
    welcomeSubtitle = "3D PHOTOGRAMMETRY & MEASUREMENT SYSTEM",
    welcomeDescription = "Map surfaces, calculate distances, areas and stockpile volumes in real-time with Augmented Reality.",
    welcomeLogin = "Log In",
    welcomeRegister = "Sign Up",
    welcomeGuest = "Continue as Guest",
    welcomeFeaturesTitle = "PROFESSIONAL MEASURING MODES",
    featureDistanceTitle = "Linear Distance Measuring",
    featureDistanceDesc = "Continuous segments with millimeter precision",
    featureAreaTitle = "Area & Perimeter Calculation",
    featureAreaDesc = "Automatic polygonal surfaces on floors and walls",
    featureVolumeTitle = "3D Volume Estimation",
    featureVolumeDesc = "LiDAR point clouds and photogrammetry for materials",

    loginTitle = "Welcome Back",
    loginSubtitle = "Sign in to access your saved measurements and projects",
    registerTitle = "Create Account",
    registerSubtitle = "Register to sync projects and measurements in the cloud",
    emailLabel = "Email Address",
    emailPlaceholder = "example@metrax.com",
    passwordLabel = "Password",
    passwordPlaceholder = "Enter your password",
    nameLabel = "Full Name",
    namePlaceholder = "Enter your name",
    confirmPasswordLabel = "Confirm Password",
    rememberMe = "Remember Me",
    forgotPassword = "Forgot Password?",
    noAccountPrompt = "Don't have an account?",
    alreadyAccountPrompt = "Already have an account?",
    socialDivider = "or continue with",
    socialRegisterDivider = "or register with",
    acceptTerms = "I agree to the Terms and Conditions of service",

    homeHeaderTitle = "Field Measurement",
    homeHeaderSubtitle = "AR camera with plane detection and 3D photogrammetry",
    modesTitle = "Measurement Modes",
    modeDistanceTitle = "Distance",
    modeDistanceDesc = "Straight lines and continuous polylines",
    modeAreaTitle = "Area",
    modeAreaDesc = "Polygonal surfaces and perimeters",
    modeVolumeTitle = "Volume",
    modeVolumeDesc = "Point clouds for stockpiles and objects",
    statsTitle = "Measurement Summary",
    statsTotal = "Total",
    statsDistance = "Distance",
    statsArea = "Area",
    statsVolume = "Volume",
    quickActionsTitle = "Quick Tools",
    actionCalibration = "Calibrate Sensor",
    actionCalibrationDesc = "Adjust scale factor with real reference targets",
    actionHistory = "Complete History",
    actionHistoryDesc = "Explore saved measurements and export reports",
    actionSettings = "Settings",
    actionSettingsDesc = "Units, haptics and app preferences",
    recentMeasurementsTitle = "Recent Measurements",
    viewAll = "View all",
    noMeasurementsYet = "No measurements recorded yet",
    startFirstMeasurement = "Start measuring using the top action buttons",
    drawerMenu = "Menu",
    drawerLanguage = "Language",
    drawerPrivacy = "Privacy Policy",
    drawerTerms = "Customer Agreement",
    drawerLogout = "Log Out",

    measureDistMode = "DISTANCE",
    measureAreaMode = "AREA",
    measureVolMode = "VOLUME",
    markPointBtn = "Mark Point",
    saveBtn = "Save",
    clearBtn = "Clear",
    calibrateBtn = "Calibrate",
    finishScan = "Finish Scanning",
    startScan = "Start LiDAR Scan",
    heightLabel = "Body Height",
    pointsCount = "points marked",
    pointCountSingle = "point marked",
    liveDistanceBadge = "live",
    onboardingTip = "Aim camera at a well-lit textured surface to detect planes",
    saveDialogTitle = "Save Measurement",
    saveTitlePlaceholder = "e.g. Living Wall, Yard Area, Sand Pile",

    settingsTitle = "Settings",
    languageSetting = "App Language",
    languageSubtitle = "Español, English, Português",
    selectLanguage = "Select Language",
    unitSystem = "Unit System",
    unitSystemMetric = "Metric (m, cm, m², m³)",
    unitSystemImperial = "Imperial (ft, in, ft², ft³)",
    showTrackingGrid = "Show Tracking Grid",
    showTrackingGridDesc = "Displays dot grid on detected surfaces",
    highQualityMode = "High Accuracy Mode",
    highQualityModeDesc = "Increased processing for enhanced tracking stability",
    hapticFeedback = "Haptic Feedback",
    hapticFeedbackDesc = "Vibrate when placing points and calibrating",
    measurementSounds = "Measurement Sounds",
    measurementSoundsDesc = "Play confirmation chime when fixing points",
    manageSubscription = "Professional Plan",
    manageSubscriptionSubtitle = "Enterprise Plan Active",
    signOut = "Sign Out",
    appVersion = "Metrax AR v1.2.0 • Multi-language & Responsive",

    historyTitle = "Measurement History",
    historySearchPlaceholder = "Search saved measurements...",
    filterAll = "All",
    filterDistance = "Distance",
    filterArea = "Area",
    filterVolume = "Volume",
    exportPdf = "Export PDF Report",
    exportCsv = "Export CSV Data",
    copyData = "Copy Data",
    share = "Share",
    deleteRecord = "Delete Measurement",
    clearAll = "Clear All",
    noResultsFound = "No measurements found",

    scanGuideTitle = "3D Scanning & Precision Guide",
    scanGuideSubtitle = "How to get millimeter accuracy with AR & LiDAR",
    scanGuideStep1Title = "1. Surface Mapping & Detection",
    scanGuideStep1Desc = "Move phone gently side to side at a 45° angle towards the surface. Avoid sudden shakes until tracking dots cover the area.",
    scanGuideStep2Title = "2. Optimal Light & Texture",
    scanGuideStep2Desc = "Ensure good lighting. AR sensors require visible textures (wood, floor, walls). Avoid plain glass or reflective mirrors.",
    scanGuideStep3Title = "3. 3D Scanning & Point Cloud",
    scanGuideStep3Desc = "For volume and 3D objects, walk slowly around the object from 1–3 meters away so LiDAR captures all sides.",
    scanGuideStep4Title = "4. Calibration & Exact Measurement",
    scanGuideStep4Desc = "Align the central crosshair precisely. Use the Calibration tool with a standard card to achieve 99.8% precision.",
    scanGuideInteractiveTest = "Interactive Scan Simulator",
    scanGuideInteractiveHint = "Drag your finger across the area to simulate the LiDAR laser sweep and detect spatial points.",
    scanGuideSurfaceDetected = "Surface Mapped with High Precision!",
    scanGuideSurfaceScanning = "Mapping surface... Drag to scan",
    scanGuideStartMeasuring = "Start Measuring!",
    scanGuideNext = "Next",
    scanGuidePrev = "Back",
    scanGuideSkip = "Skip",
    scanGuideDoNotShowAgain = "Don't show automatically again",
    scanGuideHelpTooltip = "3D Measurement Guide"
)

val PortugueseStrings = AppStrings(
    appName = "METRAX AR",
    appSubtitle = "SISTEMA AR DE MEDIÇÃO",
    appTagline = "SISTEMA DE MEDIÇÃO E FOTOGRAMETRIA 3D",
    back = "Voltar",
    cancel = "Cancelar",
    save = "Salvar",
    confirm = "Confirmar",
    delete = "Excluir",
    close = "Fechar",
    ready = "PRONTO",

    welcomeTitle = "METRAX AR",
    welcomeSubtitle = "SISTEMA DE MEDIÇÃO E FOTOGRAMETRIA 3D",
    welcomeDescription = "Mapeie superfícies, calcule distâncias, áreas e volumes de estoques em tempo real com Realidade Aumentada.",
    welcomeLogin = "Iniciar Sessão",
    welcomeRegister = "Cadastre-se",
    welcomeGuest = "Continuar como Convidado",
    welcomeFeaturesTitle = "MODOS PROFISSIONAIS DE MEDIÇÃO",
    featureDistanceTitle = "Medição Linear de Distância",
    featureDistanceDesc = "Segmentos contínuos com precisão milimétrica",
    featureAreaTitle = "Cálculo de Área e Perímetro",
    featureAreaDesc = "Superfícies poligonais automáticas em pisos e paredes",
    featureVolumeTitle = "Estimativa de Volume 3D",
    featureVolumeDesc = "Nuvens de pontos LiDAR e fotogrametria para materiais",

    loginTitle = "Bem-vindo de volta",
    loginSubtitle = "Entre com sua conta para acessar seus projetos e medições",
    registerTitle = "Criar conta",
    registerSubtitle = "Cadastre-se para sincronizar projetos na nuvem",
    emailLabel = "E-mail",
    emailPlaceholder = "exemplo@metrax.com",
    passwordLabel = "Senha",
    passwordPlaceholder = "Digite sua senha",
    nameLabel = "Nome completo",
    namePlaceholder = "Digite seu nome",
    confirmPasswordLabel = "Confirmar senha",
    rememberMe = "Lembrar de mim",
    forgotPassword = "Esqueceu a senha?",
    noAccountPrompt = "Não tem uma conta?",
    alreadyAccountPrompt = "Já tem uma conta?",
    socialDivider = "ou continuar com",
    socialRegisterDivider = "ou cadastrar-se com",
    acceptTerms = "Aceito os Termos e Condições do serviço",

    homeHeaderTitle = "Medição em Campo",
    homeHeaderSubtitle = "Câmera AR com detecção de planos e fotogrametria 3D",
    modesTitle = "Modos de Medição",
    modeDistanceTitle = "Distância",
    modeDistanceDesc = "Linhas retas e polilinhas contínuas",
    modeAreaTitle = "Área",
    modeAreaDesc = "Superfícies poligonais e perímetros",
    modeVolumeTitle = "Volume",
    modeVolumeDesc = "Nuvens de pontos para estoques e objetos",
    statsTitle = "Resumo de Medições",
    statsTotal = "Total",
    statsDistance = "Distância",
    statsArea = "Área",
    statsVolume = "Volume",
    quickActionsTitle = "Ferramentas Rápidas",
    actionCalibration = "Calibrar Sensor",
    actionCalibrationDesc = "Ajuste o fator de escala com referências reais",
    actionHistory = "Histórico Completo",
    actionHistoryDesc = "Explorar medições salvas e exportar relatórios",
    actionSettings = "Configurações",
    actionSettingsDesc = "Unidades, sensor tátil e preferências do app",
    recentMeasurementsTitle = "Medições Recentes",
    viewAll = "Ver todas",
    noMeasurementsYet = "Nenhuma medição registrada ainda",
    startFirstMeasurement = "Comece uma medição usando os botões acima",
    drawerMenu = "Menu",
    drawerLanguage = "Idioma",
    drawerPrivacy = "Política de Privacidade",
    drawerTerms = "Termos do Cliente",
    drawerLogout = "Sair da Conta",

    measureDistMode = "DISTÂNCIA",
    measureAreaMode = "ÁREA",
    measureVolMode = "VOLUME",
    markPointBtn = "Marcar Ponto",
    saveBtn = "Salvar",
    clearBtn = "Limpar",
    calibrateBtn = "Calibrar",
    finishScan = "Finalizar Escaneamento",
    startScan = "Iniciar Escaneamento LiDAR",
    heightLabel = "Altura do corpo",
    pointsCount = "pontos marcados",
    pointCountSingle = "ponto marcado",
    liveDistanceBadge = "ao vivo",
    onboardingTip = "Aponte a câmera para uma superfície bem iluminada para detectar planos",
    saveDialogTitle = "Salvar Medição",
    saveTitlePlaceholder = "Ex: Parede Sala, Terreno, Pilha de Areia",

    settingsTitle = "Configurações",
    languageSetting = "Idioma do App",
    languageSubtitle = "Español, English, Português",
    selectLanguage = "Selecionar Idioma",
    unitSystem = "Sistema de Unidades",
    unitSystemMetric = "Métrico (m, cm, m², m³)",
    unitSystemImperial = "Imperial (ft, in, ft², ft³)",
    showTrackingGrid = "Exibir Grade de Detecção",
    showTrackingGridDesc = "Exibe grade de pontos em planos detectados",
    highQualityMode = "Modo Alta Precisão",
    highQualityModeDesc = "Maior processamento para estabilidade e rastreamento",
    hapticFeedback = "Resposta Tátil (Vibração)",
    hapticFeedbackDesc = "Vibrar ao marcar pontos e calibrar",
    measurementSounds = "Sons de Medição",
    measurementSoundsDesc = "Emitir sinal sonoro ao fixar ponto",
    manageSubscription = "Plano Profissional",
    manageSubscriptionSubtitle = "Plano Corporativo Ativo",
    signOut = "Sair da Conta",
    appVersion = "Metrax AR v1.2.0 • Multi-idioma & Responsivo",

    historyTitle = "Histórico de Medições",
    historySearchPlaceholder = "Buscar medições salvas...",
    filterAll = "Todas",
    filterDistance = "Distância",
    filterArea = "Área",
    filterVolume = "Volume",
    exportPdf = "Exportar Relatório PDF",
    exportCsv = "Exportar Dados CSV",
    copyData = "Copiar Dados",
    share = "Compartilhar",
    deleteRecord = "Excluir Medição",
    clearAll = "Limpar Tudo",
    noResultsFound = "Nenhuma medição encontrada",

    scanGuideTitle = "Guia de Escaneamento e Precisão 3D",
    scanGuideSubtitle = "Como obter medições milimétricas com AR & LiDAR",
    scanGuideStep1Title = "1. Mapeamento e Detecção de Planos",
    scanGuideStep1Desc = "Mova o celular suavemente de um lado para o outro a 45° da superfície até que a grade cubra a área.",
    scanGuideStep2Title = "2. Iluminação e Textura Adequadas",
    scanGuideStep2Desc = "Garanta boa iluminação. Sensores AR precisam de texturas visíveis. Evite vidros ou espelhos lisos.",
    scanGuideStep3Title = "3. Escaneamento 3D e Nuvem de Pontos",
    scanGuideStep3Desc = "Para volumes ou pilhas 3D, caminhe devagar ao redor do objeto a 1–3 metros para capturar todas as faces.",
    scanGuideStep4Title = "4. Calibração e Medição Precisa",
    scanGuideStep4Desc = "Alinhe a mira central com exatidão. Use a Calibração com cartão para atingir 99.8% de precisão.",
    scanGuideInteractiveTest = "Simulador de Escaneamento Interativo",
    scanGuideInteractiveHint = "Arraste o dedo pela tela para simular a varredura a laser do sensor LiDAR.",
    scanGuideSurfaceDetected = "Superfície Mapeada com Alta Precisão!",
    scanGuideSurfaceScanning = "Mapeando superfície... Arraste para escanear",
    scanGuideStartMeasuring = "Começar a Medir!",
    scanGuideNext = "Próximo",
    scanGuidePrev = "Voltar",
    scanGuideSkip = "Pular",
    scanGuideDoNotShowAgain = "Não mostrar novamente automaticamente",
    scanGuideHelpTooltip = "Guia de Medição 3D"
)

object LanguageManager {
    private const val PREFS_NAME = "metrax_language_prefs"
    private const val KEY_LANG = "selected_language_code"

    private val _currentLanguage = MutableStateFlow(AppLanguage.SPANISH)
    val currentLanguage: StateFlow<AppLanguage> = _currentLanguage.asStateFlow()

    private val _currentStrings = MutableStateFlow(SpanishStrings)
    val currentStrings: StateFlow<AppStrings> = _currentStrings.asStateFlow()

    fun init(context: Context) {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        val savedCode = prefs.getString(KEY_LANG, AppLanguage.SPANISH.code) ?: AppLanguage.SPANISH.code
        val lang = AppLanguage.fromCode(savedCode)
        setLanguageInternal(lang)
    }

    fun setLanguage(context: Context, language: AppLanguage) {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        prefs.edit().putString(KEY_LANG, language.code).apply()
        setLanguageInternal(language)
    }

    private fun setLanguageInternal(language: AppLanguage) {
        _currentLanguage.value = language
        _currentStrings.value = when (language) {
            AppLanguage.SPANISH -> SpanishStrings
            AppLanguage.ENGLISH -> EnglishStrings
            AppLanguage.PORTUGUESE -> PortugueseStrings
        }
    }
}

val LocalAppStrings = compositionLocalOf { SpanishStrings }
